api:
  rate_limits:
    arxiv: 100
    pubmed: 200
    crossref: 500
  timeouts:
    default: 30
    long_running: 120

models:
  gpt4:
    max_tokens: 8000
    temperature: 0.7
  claude:
    max_tokens: 100000
    temperature: 0.5
  llama:
    model_path: "models/llama-2-70b"
    quantization: "8bit"

validation:
  confidence_threshold: 0.95
  min_sample_size: 30
  statistical_tests:
    - t_test
    - chi_square
    - anova
    - regression 